name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 1: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.4.0'  # Replace with the required version

    # Step 2: Install TFLint for linting
    - name: Install TFLint
      run: |
        curl -LO https://github.com/terraform-linters/tflint/releases/download/v0.34.0/tflint_linux_amd64.zip
        unzip tflint_linux_amd64.zip
        sudo mv tflint /usr/local/bin

    # Step 3: Run Terraform linting (TFLint)
    - name: Run TFLint
      run: tflint

    # Step 4: Initialize Terraform (gets providers, modules)
    - name: Terraform Init
      run: terraform init

    # Step 5: Terraform Plan
    - name: Terraform Plan
      run: terraform plan

    # Step 6: Apply Terraform changes (only on `main` branch and after approval)
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      if: github.ref == 'refs/heads/main'  # Only apply on the main branch

    # Optionally: Send notification or further actions after Terraform apply
